# This is a basic workflow to help you get started with Actions

name: GOODREADS

# Controls when the action will run. 
on:
  schedule: # Run workflow automatically
    - cron: "00 12 * * ?"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-current-book:
    name: Update README with my current book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          # Replace this with your goodreads user id
          goodreads_user_id: "75448858"
          shelf: "currently-reading"
          max_books_count:	"1"
